-- =============================================================================
-- 15 bài "Ghi chú luật" — BẢN NHÁP chờ duyệt (V1c mục C8).
--
-- FILE SINH TỰ ĐỘNG từ scripts/rule-notes/notes.ts — đừng sửa tay ở đây.
-- Sửa nguồn rồi chạy: npm run build:rule-notes
--
-- Nạp với published_at = null: chỉ Admin thấy. Duyệt từng bài trong
-- /admin/bai-viet, tick "Đã duyệt" rồi đăng (database chặn đăng khi chưa duyệt).
-- on conflict do nothing: dán lại không đè bài đã sửa trong admin.
-- Cần migration 20260919000001_article_knowledge.sql chạy trước.
-- =============================================================================

insert into public.articles
  (slug, title_vi, title_en, content_vi, content_en, category_id,
   access_tier, media_type, dimension, related_rules, source_references, published_at)
values
(
  'rule-res-001',
  'RES-001 — Số pixel phủ lên lỗi nhỏ nhất',
  'RES-001 — Pixels across the smallest defect',
  '<h2>Nguyên lý</h2><p>Thuật toán chỉ "thấy" một lỗi khi lỗi phủ lên đủ nhiều pixel để khác biệt rõ với nhiễu và với biên sản phẩm. Lỗi tương phản càng thấp thì càng cần nhiều pixel để phân biệt, vì mỗi pixel mang ít thông tin hơn.</p><h2>Khi nào dùng</h2><p>Mọi bài có phát hiện lỗi (ngoại quan). Luật này cho <strong>nhánh phát hiện</strong> của độ phân giải; nhánh đo lường là RES-002, và RES-003 lấy nhánh chặt hơn.</p><h2>Công thức</h2><p><code>mm/px = kích thước lỗi nhỏ nhất ÷ N</code></p><ul><li>Tương phản cao: N = 3 px</li><li>Trung bình: N = 4 px</li><li>Thấp hoặc chưa rõ: N = 5 px (phía an toàn)</li></ul><p>Khách chưa nêu tương phản thì engine lấy N = 5 và bật RES-006: phải chụp mẫu để xác nhận.</p><h2>Sai lầm thường gặp</h2><ul><li>Lấy 1 px/lỗi vì "lỗi 0,1 mm thì cần 0,1 mm/px": lỗi nằm vắt hai pixel sẽ bị chia đôi độ tương phản và lọt.</li><li>Đoán tương phản "cao" khi chưa chụp mẫu — rút N từ 5 xuống 3 làm số pixel cần giảm gần 3 lần theo diện tích.</li><li>Quên rằng N áp cho lỗi <strong>nhỏ nhất</strong>, không phải lỗi điển hình.</li></ul><h2>Ví dụ dự án</h2><p><strong>GT-002</strong> (bụi trên lớp mạ, 2025): lỗi 0,3 mm, tương phản trung bình → N = 4 → 0,075 mm/px. <strong>GT-001</strong>: lỗi 0,5 mm, tương phản chưa rõ → N = 5 → 0,1 mm/px — nhưng nhánh đo lường (0,06 mm/px) chặt hơn nên thắng.</p>',
  '<h2>Principle</h2><p>An algorithm only "sees" a defect when it covers enough pixels to stand out from noise and from part edges. The lower the contrast, the more pixels are needed, because each pixel carries less information.</p><h2>When it applies</h2><p>Every task with defect detection (appearance inspection). This rule sets the <strong>detection branch</strong> of resolution; the measurement branch is RES-002, and RES-003 keeps the tighter of the two.</p><h2>Formula</h2><p><code>mm/px = smallest defect size ÷ N</code></p><ul><li>High contrast: N = 3 px</li><li>Medium: N = 4 px</li><li>Low or unknown: N = 5 px (safe side)</li></ul><p>If the customer has not stated contrast, the engine uses N = 5 and raises RES-006: confirm with real samples.</p><h2>Common mistakes</h2><ul><li>Using 1 px per defect ("a 0.1 mm defect needs 0.1 mm/px"): a defect straddling two pixels has its contrast halved and slips through.</li><li>Assuming "high" contrast before seeing samples — dropping N from 5 to 3 cuts the required pixel count by almost 3× in area.</li><li>Forgetting that N applies to the <strong>smallest</strong> defect, not the typical one.</li></ul><h2>Project example</h2><p><strong>GT-002</strong> (dust on a plated part, 2025): 0.3 mm defect, medium contrast → N = 4 → 0.075 mm/px. <strong>GT-001</strong>: 0.5 mm defect, unknown contrast → N = 5 → 0.1 mm/px — but the measurement branch (0.06 mm/px) is tighter and wins.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Resolution',
  array['RES-001'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §4 RES-001', 'Quy ước ngành: 3–5 px trên đặc trưng nhỏ nhất (rule-of-thumb, chưa hiệu chỉnh bằng dự án của phòng)'],
  null
),
(
  'rule-res-002',
  'RES-002 — Ngân sách sai số đo lường',
  'RES-002 — Measurement uncertainty budget',
  '<h2>Nguyên lý</h2><p>"Đủ pixel để thấy" không trả lời được câu khách thật sự hỏi: <strong>±0,1 mm có đo nổi không</strong>. Hệ đo phải có sai số nhỏ hơn nhiều so với dải dung sai, nếu không thì chính hệ đo sẽ loại nhầm hàng tốt và cho qua hàng xấu. Ngân sách này (U) được chia cho mọi nguồn sai số: pixel, phối cảnh, nhiệt, ghép ảnh.</p><h2>Khi nào dùng</h2><p>Mọi bài có dung sai đo. Bài chỉ phát hiện lỗi thì không có U — các luật OPT-008, MEC-001, MEC-003 cũng không chạy.</p><h2>Công thức</h2><p><code>T = 2 × dung sai (±)</code><br /><code>U = T ÷ 10</code> (Gage R&amp;R mức tốt; 4 là tối thiểu còn chấp nhận)<br /><code>mm/px = U × 3</code> (thuật toán tìm biên nội suy được 1/3 px)</p><h2>Sai lầm thường gặp</h2><ul><li>Đặt mm/px = dung sai: hệ đo khi đó có sai số bằng cả dải dung sai.</li><li>Nhầm ± với cả dải: ±0,1 mm là dải 0,2 mm.</li><li>Tiêu hết U cho pixel rồi quên phối cảnh và giãn nở nhiệt — đó thường mới là nguồn lớn nhất (xem OPT-008, MEC-001).</li><li>Tin subpixel 1/10 px trên ảnh chưa hiệu chuẩn; 1/3 px là mức bảo toàn.</li></ul><h2>Ví dụ dự án</h2><p><strong>GT-001</strong> (vỏ nhôm 380 × 280 mm): ±0,1 mm → T = 0,2 mm → U = 0,02 mm → 0,06 mm/px. Mức này chặt hơn nhánh phát hiện lỗi (0,1 mm/px) nên quyết định độ phân giải của cả hệ.</p>',
  '<h2>Principle</h2><p>"Enough pixels to see it" does not answer the customer’s real question: <strong>can we measure ±0.1 mm?</strong> The measuring system must be much more precise than the tolerance band, or it will reject good parts and pass bad ones. This budget (U) is shared by every error source: pixels, perspective, thermal, stitching.</p><h2>When it applies</h2><p>Every task with a measurement tolerance. Pure detection tasks have no U — OPT-008, MEC-001 and MEC-003 do not run either.</p><h2>Formula</h2><p><code>T = 2 × tolerance (±)</code><br /><code>U = T ÷ 10</code> (good Gage R&amp;R; 4 is the minimum acceptable)<br /><code>mm/px = U × 3</code> (edge detection interpolates to 1/3 px)</p><h2>Common mistakes</h2><ul><li>Setting mm/px equal to the tolerance: the measuring error then spans the whole band.</li><li>Confusing ± with the full band: ±0.1 mm is a 0.2 mm band.</li><li>Spending all of U on pixels and forgetting perspective and thermal growth — often the largest sources (see OPT-008, MEC-001).</li><li>Trusting 1/10 px subpixel on an uncalibrated image; 1/3 px is the conservative figure.</li></ul><h2>Project example</h2><p><strong>GT-001</strong> (380 × 280 mm aluminium housing): ±0.1 mm → T = 0.2 mm → U = 0.02 mm → 0.06 mm/px. This is tighter than the detection branch (0.1 mm/px) and sets the resolution of the whole system.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Resolution',
  array['RES-002'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §3.3, §4 RES-002', 'AIAG MSA Reference Manual (4th ed.) — quy ước Gage R&R ≤ 10 % dải dung sai', 'Hằng số GRR_DIVISOR = 10, K_SUBPIXEL = 3 (src/lib/vision/resolution.ts)'],
  null
),
(
  'rule-res-004',
  'RES-004 — Số pixel cần cho mỗi camera',
  'RES-004 — Pixels required per camera',
  '<h2>Nguyên lý</h2><p>Khi đã có mm/px mục tiêu (RES-003), số pixel mỗi camera là vùng nhìn của camera đó chia cho mm/px, tính <strong>riêng từng trục</strong>. Camera phải có đủ pixel trên cả hai trục — một cảm biến 20 MP tỉ lệ 3:2 có thể vẫn thiếu pixel cho vùng nhìn gần vuông.</p><h2>Khi nào dùng</h2><p>Mọi bài có vùng nhìn và mm/px mục tiêu. Nhiều camera thì vùng nhìn là một ô lưới (RES-005), đã cộng chồng lấn.</p><h2>Công thức</h2><p><code>nx = ⌈rộng ô ÷ mm/px⌉</code>, <code>ny = ⌈cao ô ÷ mm/px⌉</code>, <code>MP = nx × ny ÷ 10⁶</code></p><p>Camera nghiêng θ (OPT-009): cạnh dài dùng <code>mm/px × cos θ</code> — pixel trên vật dài ra 1/cos θ theo chiều nghiêng.</p><h2>Sai lầm thường gặp</h2><ul><li>So sánh bằng megapixel: MP tỉ lệ với <strong>bình phương</strong> độ phân giải. Dư 61 % MP chỉ là dư 27 % mm/px.</li><li>Chỉ tính trục ngang rồi báo dư — phải tính theo trục thô hơn, vì kích thước cần đo nằm theo trục bất kỳ.</li><li>Quên chồng lấn giữa các camera, làm mỗi camera thiếu pixel ở mép.</li></ul><h2>Ví dụ dự án</h2><p><strong>GT-001</strong>: 4 camera lưới 2×2, mỗi ô 209 × 154 mm, 0,06 mm/px → 3484 × 2567 px = 8,94 MP/camera. <strong>GT-002</strong>: vật 80 × 55 mm, camera nghiêng 30°, 0,075 mm/px → 80 ÷ (0,075 × cos 30°) = 1232 px × 55 ÷ 0,075 = 734 px = 0,90 MP.</p>',
  '<h2>Principle</h2><p>Once the target mm/px is known (RES-003), the pixels per camera are that camera’s field of view divided by mm/px, <strong>per axis</strong>. The camera needs enough pixels on both axes — a 20 MP 3:2 sensor can still fall short on a nearly square field.</p><h2>When it applies</h2><p>Every task with a field of view and a target mm/px. With several cameras the field is one grid tile (RES-005), overlap included.</p><h2>Formula</h2><p><code>nx = ⌈tile width ÷ mm/px⌉</code>, <code>ny = ⌈tile height ÷ mm/px⌉</code>, <code>MP = nx × ny ÷ 10⁶</code></p><p>Camera tilted by θ (OPT-009): the long side uses <code>mm/px × cos θ</code> — a pixel on the part stretches by 1/cos θ along the tilt.</p><h2>Common mistakes</h2><ul><li>Comparing in megapixels: MP scales with the <strong>square</strong> of resolution. 61 % more MP is only 27 % more mm/px headroom.</li><li>Checking only the horizontal axis and reporting headroom — use the coarser axis, since the measured feature can lie along either.</li><li>Forgetting overlap between cameras, leaving each camera short at the edges.</li></ul><h2>Project example</h2><p><strong>GT-001</strong>: 4 cameras in a 2×2 grid, each tile 209 × 154 mm, 0.06 mm/px → 3484 × 2567 px = 8.94 MP per camera. <strong>GT-002</strong>: 80 × 55 mm part, camera tilted 30°, 0.075 mm/px → 80 ÷ (0.075 × cos 30°) = 1232 px × 55 ÷ 0.075 = 734 px = 0.90 MP.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Resolution',
  array['RES-004'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §4 RES-004', 'docs/UI_CONTENT_V1.md màn 5 — dư độ phân giải tính trên mm/px, không trên MP'],
  null
),
(
  'rule-res-005',
  'RES-005 — Chia vùng nhìn cho nhiều camera',
  'RES-005 — Splitting the field across cameras',
  '<h2>Nguyên lý</h2><p>Khi một camera không đủ pixel, vùng nhìn được chia thành lưới, mỗi camera nhìn một ô cộng phần chồng lấn với ô kề. Kích thước MỘT ô — không phải cả vật — là đầu vào của mọi phép tính theo từng camera: số pixel (RES-004), sai số phối cảnh (OPT-008), chọn ống kính (OPT-001).</p><h2>Khi nào dùng</h2><p>Mọi bài có số camera. Chưa nhập số camera thì engine <strong>không tự đoán</strong>: báo cảnh báo kèm số MP nếu chỉ dùng một camera, để kỹ sư quyết định.</p><h2>Công thức</h2><ul><li>Lưới gần vuông nhất đúng bằng số camera: 1 → 1×1, 2 → 2×1, 4 → 2×2, 6 → 3×2; chiều nhiều camera hơn nằm theo cạnh dài của vật.</li><li>Chồng lấn mỗi ô: lớn hơn của 10 % bề rộng ô và 20 px.</li></ul><h2>Sai lầm thường gặp</h2><ul><li>Lấy nửa đường chéo cả vật để tính phối cảnh cho hệ nhiều camera — thổi phồng sai số gấp đôi với lưới 2×2.</li><li>Không chừa chồng lấn: lỗi nằm đúng đường ghép bị cắt đôi giữa hai ảnh.</li><li>Thêm camera để "dư pixel" mà quên mỗi đường ghép thêm một nguồn sai số hiệu chuẩn (MEC-003).</li></ul><h2>Ví dụ dự án</h2><p><strong>GT-001</strong>: vật 380 × 280 mm, 4 camera → lưới 2×2, ô 190 × 140 mm + 10 % chồng lấn = 209 × 154 mm mỗi camera.</p>',
  '<h2>Principle</h2><p>When one camera lacks pixels, the field is split into a grid; each camera sees one tile plus overlap with its neighbours. The size of ONE tile — not the whole part — feeds every per-camera calculation: pixel count (RES-004), perspective error (OPT-008), lens selection (OPT-001).</p><h2>When it applies</h2><p>Every task with a camera count. If the count is missing the engine <strong>does not guess</strong>: it warns and shows the MP needed with a single camera so the engineer decides.</p><h2>Formula</h2><ul><li>The most nearly square grid with exactly n cameras: 1 → 1×1, 2 → 2×1, 4 → 2×2, 6 → 3×2; the axis with more cameras runs along the long side of the part.</li><li>Overlap per tile: the larger of 10 % of the tile width and 20 px.</li></ul><h2>Common mistakes</h2><ul><li>Using the half-diagonal of the whole part for perspective in a multi-camera system — doubles the error for a 2×2 grid.</li><li>No overlap: a defect exactly on the seam is cut in half between two images.</li><li>Adding cameras for "spare pixels" while forgetting each seam adds a calibration error (MEC-003).</li></ul><h2>Project example</h2><p><strong>GT-001</strong>: 380 × 280 mm part, 4 cameras → 2×2 grid, tiles 190 × 140 mm + 10 % overlap = 209 × 154 mm per camera.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Resolution',
  array['RES-005'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §4.1 RES-005', 'Hằng số TILE_OVERLAP_RATIO = 0,1, TILE_OVERLAP_MIN_PX = 20 (src/lib/vision/tiling.ts)'],
  null
),
(
  'rule-mec-001',
  'MEC-001 — Giãn nở nhiệt trong đo lường',
  'MEC-001 — Thermal expansion in measurement',
  '<h2>Nguyên lý</h2><p>Vật đo dài ra khi nóng lên. Với span dài, sai số giãn nở có thể lớn hơn cả ngân sách đo — và <strong>tăng megapixel không làm vật bớt giãn nở</strong>. Đây là giới hạn cơ khí, không phải giới hạn camera.</p><h2>Khi nào dùng</h2><p>Bài có dung sai đo (có U — RES-002). Engine cần α (vật liệu), chiều dài cần đo L và dao động nhiệt ΔT; thiếu thì giả định phía xấu: L = cạnh dài nhất của vật, α = 23 (nhôm), ΔT = 10 K (xưởng không điều hoà) — và ghi rõ trong panel Giả định.</p><h2>Công thức</h2><p><code>sai số = α × L × ΔT</code> (µm, với α tính bằng µm/(m·K), L bằng m, ΔT bằng K)</p><ul><li>&gt; U → không đạt; &gt; 50 % U → cảnh báo (các nguồn khác còn quá ít chỗ).</li><li>Dao động nhiệt cho phép: <code>ΔT_max = U ÷ (α × L)</code> — con số để làm việc với khách.</li></ul><p>ΔT là <strong>cả dải</strong> dao động: ΔT_max = 2,3 K nghĩa là giữ trong ±1,15 K.</p><h2>Sai lầm thường gặp</h2><ul><li>Hiệu chuẩn buổi sáng, đo buổi chiều trong xưởng không điều hoà.</li><li>Đọc ΔT_max là ± rồi cho phép gấp đôi.</li><li>Tưởng bù nhiệt bằng phần mềm là miễn phí: cần cảm biến nhiệt độ trên chính vật, không phải không khí.</li></ul><h2>Ví dụ dự án</h2><p><strong>GT-001</strong>: vỏ nhôm, span 380 mm, ΔT 10 K → 23 × 0,38 × 10 = 87,4 µm, gấp khoảng 4,4 lần U = 20 µm → không đạt. Muốn đạt phải giữ dao động nhiệt dưới 2,29 K (±1,14 K), hoặc đo so sánh với chuẩn cùng vật liệu.</p>',
  '<h2>Principle</h2><p>Parts grow as they warm up. Over a long span the thermal error can exceed the whole measurement budget — and <strong>more megapixels do not make the part expand less</strong>. This is a mechanical limit, not a camera limit.</p><h2>When it applies</h2><p>Tasks with a measurement tolerance (a U from RES-002). The engine needs α (material), the measured length L and the temperature swing ΔT; when missing it assumes the worst side: L = longest side of the part, α = 23 (aluminium), ΔT = 10 K (no air conditioning) — and says so in the Assumptions panel.</p><h2>Formula</h2><p><code>error = α × L × ΔT</code> (µm, with α in µm/(m·K), L in m, ΔT in K)</p><ul><li>&gt; U → fail; &gt; 50 % of U → warning (too little room left for other sources).</li><li>Allowed swing: <code>ΔT_max = U ÷ (α × L)</code> — the number to discuss with the customer.</li></ul><p>ΔT is the <strong>full</strong> swing: ΔT_max = 2.3 K means holding within ±1.15 K.</p><h2>Common mistakes</h2><ul><li>Calibrating in the morning and measuring in the afternoon in a shop without air conditioning.</li><li>Reading ΔT_max as ± and allowing twice as much.</li><li>Assuming software compensation is free: it needs a temperature sensor on the part itself, not in the air.</li></ul><h2>Project example</h2><p><strong>GT-001</strong>: aluminium housing, 380 mm span, ΔT 10 K → 23 × 0.38 × 10 = 87.4 µm, about 4.4× U = 20 µm → fail. Passing requires holding the swing under 2.29 K (±1.14 K), or comparative measurement against a master of the same material.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Mechanical',
  array['MEC-001'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §6 MEC-001', 'Hệ số giãn nở dài α tra theo vật liệu (nhôm ≈ 23, thép ≈ 12 µm/(m·K))', 'Ngưỡng ERROR_WARN_SHARE = 0,5 (src/lib/vision/resolution.ts)'],
  null
),
(
  'rule-opt-001',
  'OPT-001 — Vùng nhìn thực của camera + ống kính',
  'OPT-001 — Actual field of view of camera + lens',
  '<h2>Nguyên lý</h2><p>Một cặp camera + ống kính ở khoảng cách làm việc WD cho ra một độ phóng đại β. Từ β suy ra vùng nhìn thực và mm/px thực. Cặp đạt khi <strong>vừa phủ đủ vùng nhìn, vừa đủ mịn</strong> — hai điều kiện kéo ngược nhau: tiêu cự dài thì mịn nhưng hụt vùng nhìn, ngắn thì phủ rộng nhưng thô.</p><h2>Khi nào dùng</h2><p>Tầng Cấu hình: chạy trên mọi cặp camera + ống kính trong kho. Hệ số dư của luật này (mục tiêu ÷ mm/px thực) là thứ xếp cặp vào ba mức Tiết kiệm / Đề xuất / Dư an toàn.</p><h2>Công thức</h2><p><code>β = f ÷ (WD − f)</code> (ống telecentric: β là độ phóng đại ghi trên ống)<br /><code>vùng nhìn = kích thước cảm biến ÷ β</code><br /><code>mm/px thực = pitch ÷ β</code><br /><code>tiêu cự lý tưởng = WD × β ÷ (1 + β)</code></p><p>Không đạt khi: camera ít pixel đến mức không β nào vừa phủ vừa đủ mịn; vùng nhìn hụt; hoặc mm/px thực thô hơn mục tiêu. WD gần hơn khoảng lấy nét tối thiểu của ống cũng không đạt.</p><h2>Sai lầm thường gặp</h2><ul><li>Chọn tiêu cự theo bảng của hãng mà quên WD tính từ đâu.</li><li>Gọi ống telecentric bằng tiêu cự ("telecentric 35 mm") — telecentric quy định bằng độ phóng đại.</li><li>Báo dư theo trục ngang trong khi trục dọc mới là trục thô.</li></ul><h2>Ví dụ dự án</h2><p><strong>GT-002</strong>: camera 20 MP pitch 2,4 µm + ống 25 mm, WD 200 mm → β = 25 ÷ 175 → engine tính vùng nhìn 91,9 × 61,3 mm, vẫn phủ vật 80 × 55 mm. Thực tế đo được 105 × 70 mm, lệch khoảng 13 % vì WD đo từ mặt ống chứ không từ điểm chính của thấu kính — mô hình thấu kính mỏng cho số thận trọng.</p>',
  '<h2>Principle</h2><p>A camera + lens pair at working distance WD gives a magnification β. From β follow the actual field of view and the actual mm/px. A pair passes when it <strong>both covers the field and resolves finely enough</strong> — two conditions that pull against each other: a long focal length is fine but covers too little, a short one covers a lot but coarsely.</p><h2>When it applies</h2><p>Configuration layer: runs on every camera + lens pair in the catalogue. This rule’s headroom (target ÷ actual mm/px) is what sorts pairs into the Economy / Recommended / High-margin levels.</p><h2>Formula</h2><p><code>β = f ÷ (WD − f)</code> (telecentric lens: β is the magnification printed on the lens)<br /><code>field = sensor size ÷ β</code><br /><code>actual mm/px = pitch ÷ β</code><br /><code>ideal focal length = WD × β ÷ (1 + β)</code></p><p>Fails when the camera has so few pixels that no β both covers and resolves; when the field falls short; or when the actual mm/px is coarser than the target. A WD closer than the lens’s minimum focus distance also fails.</p><h2>Common mistakes</h2><ul><li>Picking a focal length from a vendor chart without checking where WD is measured from.</li><li>Naming a telecentric lens by focal length ("35 mm telecentric") — telecentrics are specified by magnification.</li><li>Reporting headroom on the horizontal axis when the vertical axis is the coarse one.</li></ul><h2>Project example</h2><p><strong>GT-002</strong>: 20 MP camera with 2.4 µm pitch + 25 mm lens, WD 200 mm → β = 25 ÷ 175 → the engine computes a 91.9 × 61.3 mm field, still covering the 80 × 55 mm part. The real field was 105 × 70 mm, about 13 % larger, because WD was measured from the lens front rather than the principal point — the thin-lens model errs on the conservative side.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Optics',
  array['OPT-001'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §8.1 OPT-001', 'Mô hình thấu kính mỏng: β = f ÷ (WD − f)', 'src/lib/vision/configurationRules.ts'],
  null
),
(
  'rule-opt-002',
  'OPT-002 — Vòng ảnh và ngàm ống kính',
  'OPT-002 — Image circle and lens mount',
  '<h2>Nguyên lý</h2><p>Ống kính chỉ tạo ảnh sắc nét trong một vòng tròn (image circle). Cảm biến lớn hơn vòng ảnh thì bốn góc tối và mờ (vignetting). Ngàm quyết định ống có lắp được và lấy nét được trên camera hay không.</p><h2>Khi nào dùng</h2><p>Tầng Cấu hình, mọi cặp camera + ống kính. Luật đạt / không đạt — không có "hệ số dư".</p><h2>Công thức</h2><ul><li><code>vòng ảnh ống ≥ đường chéo cảm biến</code> (cho phép lệch 2 % vì số trên datasheet đã làm tròn).</li><li>Ngàm phải khớp. Ống C lên camera CS: được, thêm vòng đệm 5 mm (cảnh báo). Ống CS lên camera C: không lấy nét được (không đạt).</li></ul><h2>Sai lầm thường gặp</h2><ul><li>Đọc cỡ cảm biến theo tên ("1.1 inch") thay vì tính từ số pixel × pitch — tên gọi và kích thước thật có thể lệch.</li><li>Dùng ống 2/3" cho cảm biến 1.1" rồi cắt ROI để "chữa" — mất đúng số pixel đã trả tiền.</li><li>Quên vòng đệm C→CS khi đặt hàng.</li></ul><h2>Ví dụ dự án</h2><p>Minh hoạ: cảm biến 5472 × 3648 px pitch 2,4 µm = 13,1 × 8,8 mm, đường chéo khoảng 15,8 mm — cần ống vòng ảnh từ 16 mm trở lên (cỡ 1"), ống 2/3" (11 mm) sẽ tối góc.</p>',
  '<h2>Principle</h2><p>A lens forms a sharp image only inside a circle (the image circle). If the sensor is larger, the corners go dark and soft (vignetting). The mount decides whether the lens fits and can focus on the camera at all.</p><h2>When it applies</h2><p>Configuration layer, every camera + lens pair. A pass/fail rule — no "headroom".</p><h2>Formula</h2><ul><li><code>lens image circle ≥ sensor diagonal</code> (2 % allowance because datasheet figures are rounded).</li><li>Mounts must match. C lens on a CS camera: OK with a 5 mm spacer (warning). CS lens on a C camera: cannot focus (fail).</li></ul><h2>Common mistakes</h2><ul><li>Taking the sensor size from its name ("1.1 inch") instead of pixel count × pitch — the name and the real size can differ.</li><li>Using a 2/3" lens on a 1.1" sensor and cropping an ROI to "fix" it — throwing away exactly the pixels you paid for.</li><li>Forgetting the C→CS spacer on the order.</li></ul><h2>Project example</h2><p>Illustration: a 5472 × 3648 px sensor with 2.4 µm pitch is 13.1 × 8.8 mm, diagonal about 15.8 mm — it needs an image circle of 16 mm or more (1" class); a 2/3" lens (11 mm) will vignette.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Optics',
  array['OPT-002'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §8.1 OPT-002', 'Hằng số IMAGE_CIRCLE_TOLERANCE = 0,02 (src/lib/vision/configurationRules.ts)', 'Khoảng cách mặt bích: C 17,526 mm, CS 12,526 mm'],
  null
),
(
  'rule-opt-004',
  'OPT-004 — Giới hạn nhiễu xạ (F#max)',
  'OPT-004 — Diffraction limit (F#max)',
  '<h2>Nguyên lý</h2><p>Khép khẩu (tăng số F) làm tăng độ sâu trường ảnh nhưng làm đốm sáng nhiễu xạ (đĩa Airy) to ra. Khi đĩa Airy lớn hơn khoảng hai pixel, ảnh mờ đi dù ống kính tốt đến đâu — pixel càng nhỏ, giới hạn này đến càng sớm.</p><h2>Khi nào dùng</h2><p>Tầng Cấu hình, mọi cặp camera + ống kính. Luật này cho F#max của camera; OPT-005 dùng F#max để xét độ sâu trường ảnh.</p><h2>Công thức</h2><p><code>F#max = 2 × pitch ÷ (2,44 × λ)</code>, λ = 0,55 µm (ánh sáng xanh lá)</p><ul><li>Pitch 3,45 µm → F#max ≈ 5,1</li><li>Pitch 2,4 µm → F#max ≈ 3,6</li></ul><p>Không đạt khi khẩu mở lớn nhất của ống (F nhỏ nhất) đã lớn hơn F#max — ống quá "chậm" cho pixel này.</p><h2>Sai lầm thường gặp</h2><ul><li>Khép F/8–F/11 cho "nét sâu" trên camera pixel 2,4 µm — ảnh mờ do nhiễu xạ, rồi đổ lỗi cho ống kính.</li><li>Mua camera pixel nhỏ để tăng MP mà không đổi ống: lp/mm của ống (OPT-003) và F#max đều siết lại.</li><li>Dùng đèn hồng ngoại (λ dài hơn) mà không tính lại F#max.</li></ul><h2>Ví dụ dự án</h2><p>Minh hoạ: camera pixel 3,45 µm → F#max ≈ 5,1. Ống F/1.4–F/16 đạt (mở được tới F/1.4), nhưng khi vận hành không nên khép quá khoảng F/5.</p>',
  '<h2>Principle</h2><p>Stopping down (higher F-number) increases depth of field but enlarges the diffraction spot (Airy disk). Once the Airy disk exceeds about two pixels the image softens however good the lens is — the smaller the pixel, the sooner this limit arrives.</p><h2>When it applies</h2><p>Configuration layer, every camera + lens pair. This rule gives the camera’s F#max; OPT-005 uses F#max to check depth of field.</p><h2>Formula</h2><p><code>F#max = 2 × pitch ÷ (2.44 × λ)</code>, λ = 0.55 µm (green light)</p><ul><li>3.45 µm pitch → F#max ≈ 5.1</li><li>2.4 µm pitch → F#max ≈ 3.6</li></ul><p>Fails when the lens’s widest aperture (smallest F) is already above F#max — the lens is too "slow" for this pixel.</p><h2>Common mistakes</h2><ul><li>Stopping down to F/8–F/11 "for depth" on a 2.4 µm camera — the image blurs from diffraction and the lens gets blamed.</li><li>Buying a smaller-pixel camera for more MP without changing the lens: both lens lp/mm (OPT-003) and F#max tighten.</li><li>Switching to infrared (longer λ) without recomputing F#max.</li></ul><h2>Project example</h2><p>Illustration: a 3.45 µm camera → F#max ≈ 5.1. An F/1.4–F/16 lens passes (it opens to F/1.4), but in operation it should not be stopped down past about F/5.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Optics',
  array['OPT-004'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §8.1 OPT-004', 'Đĩa Airy: đường kính ≈ 2,44 × λ × F#', 'Hằng số WAVELENGTH_UM = 0,55 (src/lib/vision/optics.ts)'],
  null
),
(
  'rule-opt-005',
  'OPT-005 — Độ sâu trường ảnh và khẩu',
  'OPT-005 — Depth of field and aperture',
  '<h2>Nguyên lý</h2><p>Vật cao thấp khác nhau (Δh), hoặc camera nhìn nghiêng, thì các điểm trên vật nằm ở độ xa khác nhau — cần độ sâu trường ảnh đủ để tất cả cùng nét. Muốn sâu thì khép khẩu, nhưng khép quá F#max (OPT-004) thì nhiễu xạ làm mờ. Luật này đặt hai yêu cầu đó cạnh nhau.</p><h2>Khi nào dùng</h2><p>Tầng Cấu hình, khi đã biết dao động chiều cao Δh. Camera nghiêng thì độ sâu cần cộng thêm <code>cạnh dài × sin θ</code>.</p><h2>Công thức</h2><p><code>F cần = DOF × β² ÷ (2 × c × (1 + β))</code>, với <code>c = 2 × pitch</code> và <code>DOF = Δh + cạnh dài × sin θ</code></p><ul><li>F cần ≤ F#max → đạt; F cần nhỏ hơn khẩu mở nhất của ống → khẩu nào cũng đủ.</li><li>F#max &lt; F cần ≤ 1,5 × F#max → cảnh báo: mờ nhẹ, phải chụp thử.</li><li>&gt; 1,5 × F#max → xung đột, <strong>không đổi ống nào giải được</strong>; hoặc ống không khép tới F cần.</li></ul><h2>Sai lầm thường gặp</h2><ul><li>Giải xung đột bằng cách khép thêm khẩu — chỉ đổi mờ do mất nét lấy mờ do nhiễu xạ.</li><li>Quên phần độ sâu do camera nghiêng; góc nghiêng lớn thường chiếm phần lớn DOF.</li><li>Hướng xử lý đúng: giảm Δh bằng đồ gá, tăng WD kèm tiêu cự dài hơn, dùng telecentric, ống Scheimpflug khi nghiêng, hoặc chụp nhiều mặt nét.</li></ul><h2>Ví dụ dự án</h2><p><strong>GT-002</strong>: camera nghiêng 30° trên vật dài 80 mm → phần độ sâu do nghiêng 80 × sin 30° = 40 mm; engine đòi khép tới khoảng F/78, gấp hơn 20 lần F#max, nên báo xung đột. Dự án thật vẫn chạy đạt — nghĩa là công thức vòng nhoè hiện tại quá thận trọng cho bài phát hiện bụi. Đây là điểm đã ghi nhận để hiệu chỉnh sau (knownGaps của GT-002), kỹ sư cần đọc cảnh báo này cùng chụp mẫu thật.</p>',
  '<h2>Principle</h2><p>When part height varies (Δh), or the camera looks at an angle, points on the part sit at different distances — the depth of field must keep them all sharp. More depth means stopping down, but beyond F#max (OPT-004) diffraction blurs. This rule puts both demands side by side.</p><h2>When it applies</h2><p>Configuration layer, once the height variation Δh is known. With a tilted camera the required depth adds <code>long side × sin θ</code>.</p><h2>Formula</h2><p><code>F needed = DOF × β² ÷ (2 × c × (1 + β))</code>, with <code>c = 2 × pitch</code> and <code>DOF = Δh + long side × sin θ</code></p><ul><li>F needed ≤ F#max → pass; below the lens’s widest aperture → any aperture works.</li><li>F#max &lt; F needed ≤ 1.5 × F#max → warning: slight blur, test with samples.</li><li>&gt; 1.5 × F#max → conflict that <strong>no lens change can solve</strong>; or the lens cannot stop down that far.</li></ul><h2>Common mistakes</h2><ul><li>"Solving" the conflict by stopping down further — trading defocus blur for diffraction blur.</li><li>Forgetting the depth added by camera tilt; at large angles it is often most of the DOF.</li><li>Real fixes: reduce Δh with fixturing, raise WD with a longer focal length, use a telecentric, a Scheimpflug lens when tilted, or focus stacking.</li></ul><h2>Project example</h2><p><strong>GT-002</strong>: camera tilted 30° over an 80 mm part → tilt depth 80 × sin 30° = 40 mm; the engine asks for about F/78, more than 20× F#max, and reports a conflict. The real project still passed — meaning the current circle-of-confusion formula is too conservative for dust detection. This is a recorded gap to calibrate later (GT-002 knownGaps); engineers should read this warning together with real sample shots.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Optics',
  array['OPT-005'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §8.1 OPT-005', 'Công thức độ sâu trường ảnh gần đúng, vòng nhoè c = 2 px (DEFAULT_CIRCLE_OF_CONFUSION_PX)', 'Hằng số DOF_DIFFRACTION_TOLERANCE = 1,5 (src/lib/vision/configurationRules.ts)'],
  null
),
(
  'rule-opt-008',
  'OPT-008 — Sai số phối cảnh của ống kính thường',
  'OPT-008 — Perspective error of a standard lens',
  '<h2>Nguyên lý</h2><p>Ống kính thường (entocentric) nhìn theo hình nón: điểm nằm cao hơn trông như dịch ra xa tâm ảnh. Nếu chiều cao vật dao động, vị trí biên đo được dịch theo — sai số này <strong>không giảm khi tăng megapixel</strong>. Càng xa tâm và WD càng ngắn thì càng lớn.</p><h2>Khi nào dùng</h2><p>Bài có dung sai đo (có U) và biết dao động chiều cao Δh cùng WD. Khách yêu cầu đo "không phối cảnh" thì chuyển sang OPT-006: bắt buộc telecentric.</p><h2>Công thức</h2><p><code>sai số = Δh ÷ WD × r</code>, r = nửa đường chéo vùng nhìn của MỘT camera</p><ul><li>&gt; U → không đạt; &gt; 50 % U → cảnh báo.</li></ul><h2>Sai lầm thường gặp</h2><ul><li>Tính r theo cả vật với hệ nhiều camera — sai số bị thổi phồng.</li><li>Nghĩ hiệu chuẩn một mặt phẳng là đủ: hiệu chuẩn chỉ đúng ở đúng chiều cao đó.</li><li>Nhảy ngay sang telecentric mà không xét OPT-007: vùng nhìn trên 200 mm thì telecentric gần như không khả thi.</li><li>Cách giảm: tăng WD, kẹp chặt Δh bằng đồ gá, đo chiều cao để bù, hoặc chia nhiều camera nhỏ hơn.</li></ul><h2>Ví dụ dự án</h2><p><strong>GT-001</strong>: Δh 2 mm, WD 300 mm, nửa đường chéo ô 129,8 mm → 2 ÷ 300 × 129,8 = 0,865 mm, gấp khoảng 43 lần U = 0,02 mm → không đạt. Telecentric cho ô 209 mm cũng vượt giới hạn 200 mm (OPT-007) — dự án phải xử lý bằng cơ khí.</p>',
  '<h2>Principle</h2><p>A standard (entocentric) lens views in a cone: a higher point appears shifted away from the image centre. If part height varies, the measured edge position shifts with it — an error that <strong>does not shrink with more megapixels</strong>. It grows further from the centre and at shorter WD.</p><h2>When it applies</h2><p>Tasks with a measurement tolerance (a U) and known height variation Δh and WD. If the customer requires "perspective-free" measurement, OPT-006 applies instead: telecentric is mandatory.</p><h2>Formula</h2><p><code>error = Δh ÷ WD × r</code>, r = half-diagonal of ONE camera’s field</p><ul><li>&gt; U → fail; &gt; 50 % of U → warning.</li></ul><h2>Common mistakes</h2><ul><li>Using the whole part for r in a multi-camera system — inflates the error.</li><li>Thinking one flat-plane calibration is enough: it is only valid at that height.</li><li>Jumping straight to telecentric without checking OPT-007: above a 200 mm field, telecentric is hardly feasible.</li><li>Ways out: raise WD, clamp Δh with fixturing, measure height and compensate, or use more, smaller camera fields.</li></ul><h2>Project example</h2><p><strong>GT-001</strong>: Δh 2 mm, WD 300 mm, tile half-diagonal 129.8 mm → 2 ÷ 300 × 129.8 = 0.865 mm, about 43× U = 0.02 mm → fail. A telecentric for a 209 mm tile is also beyond the 200 mm limit (OPT-007) — the project must be solved mechanically.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Optics',
  array['OPT-008'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §4 OPT-008', 'Hình học chiếu phối cảnh: sai số = Δh ÷ WD × r', 'Ngưỡng ERROR_WARN_SHARE = 0,5 (src/lib/vision/resolution.ts)'],
  null
),
(
  'rule-lgt-001',
  'LGT-001 — Chiếu sáng bề mặt bóng, phản xạ',
  'LGT-001 — Lighting glossy, reflective surfaces',
  '<h2>Nguyên lý</h2><p>Bề mặt bóng như gương phản chiếu nguồn sáng thẳng vào camera: chỗ thì loá trắng, chỗ thì tối đen, lỗi chìm trong phản xạ. Với bề mặt này, <strong>bề mặt quyết định kiểu đèn trước loại lỗi</strong> — dark field để soi xước trên mặt gương chỉ cho thấy loá.</p><h2>Khi nào dùng</h2><p>Bề mặt bóng hoặc kim loại (engine cũng dùng mã này cho gợi ý chiếu sáng của lỗi trên mặt cong bóng và lỗi in / màu). Luật luôn đi kèm "cần chụp mẫu": chiếu sáng là bảng tra kinh nghiệm, không phải công thức, và không kết luận được nếu chưa chụp mẫu thật.</p><h2>Công thức</h2><ul><li>Đề xuất chính: <strong>dome</strong> khuếch tán — ánh sáng đều từ mọi hướng, triệt phản xạ điểm.</li><li>Thay thế: <strong>tấm đèn phẳng diện rộng (backlight)</strong> đặt đúng góc phản xạ gương, để bề mặt phản chiếu một nền sáng đều vào camera — lỗi hiện thành chấm tối.</li><li>Đèn phải phủ được đường chéo vùng nhìn (kiểm ở bước lọc thiết bị).</li></ul><h2>Sai lầm thường gặp</h2><ul><li>Dùng đèn vòng hoặc đèn thanh chiếu thẳng — thấy chính bóng đèn trên sản phẩm.</li><li>Dome nhỏ hơn vùng nhìn — mép ảnh thiếu sáng, lộ lỗ camera ở tâm.</li><li>Chốt đèn qua catalog mà không chụp mẫu trên đúng lớp mạ / sơn của khách.</li></ul><h2>Ví dụ dự án</h2><p><strong>GT-002</strong> (bụi trên lớp mạ nhựa): dự án thật dùng tấm backlight 200 × 200 mm phía trên cách 200 mm và tấm 200 × 100 mm dựng bên cạnh cách 100 mm, camera nghiêng khoảng 25–35° — tức tấm sáng phẳng ở góc phản xạ gương, không dùng dome. Bụi hiện thành chấm tối trên nền sáng đều.</p>',
  '<h2>Principle</h2><p>A mirror-like surface reflects the light source straight into the camera: some areas blow out white, others go black, and defects drown in reflections. On such surfaces <strong>the surface decides the light before the defect type does</strong> — dark field for scratches on a mirror only shows glare.</p><h2>When it applies</h2><p>Glossy or metallic surfaces (the engine also uses this ID for the lighting suggestion for defects on glossy curved parts and print / colour defects). The rule always carries "needs sample test": lighting is an experience table, not a formula, and cannot be concluded without shooting real samples.</p><h2>Formula</h2><ul><li>Primary: a diffuse <strong>dome</strong> — even light from every direction, killing point reflections.</li><li>Alternative: a <strong>large flat panel (backlight)</strong> placed at the specular angle, so the surface mirrors an even bright background into the camera — defects show as dark spots.</li><li>The light must cover the field diagonal (checked during equipment filtering).</li></ul><h2>Common mistakes</h2><ul><li>Ring or bar lights aimed straight on — you see the lamp itself on the part.</li><li>A dome smaller than the field — dark edges, and the camera hole shows in the centre.</li><li>Choosing the light from a catalogue without shooting samples of the customer’s actual plating or paint.</li></ul><h2>Project example</h2><p><strong>GT-002</strong> (dust on plated plastic): the real project used a 200 × 200 mm backlight above at 200 mm and a 200 × 100 mm panel standing beside at 100 mm, camera tilted about 25–35° — flat panels at the specular angle, no dome. Dust showed as dark spots on an even bright background.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Lighting',
  array['LGT-001'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §4 LGT', 'Bảng tra kinh nghiệm chiếu sáng (src/lib/vision/lighting.ts)', 'Dự án GT-002 (2025) — tấm sáng phẳng ở góc phản xạ gương'],
  null
),
(
  'rule-lgt-002',
  'LGT-002 — Chiếu sáng cho vết xước và lõm nông',
  'LGT-002 — Lighting for scratches and shallow dents',
  '<h2>Nguyên lý</h2><p>Vết xước và vết lõm hầu như không đổi màu — chúng chỉ đổi <strong>hướng</strong> của bề mặt. Muốn thấy chúng phải dùng ánh sáng xiên để chỗ lệch hướng hắt sáng vào camera (hoặc hắt ra khỏi camera) khác hẳn phần phẳng xung quanh.</p><h2>Khi nào dùng</h2><p>Loại lỗi là vết xước hoặc lõm lồi nông, trên bề mặt <strong>không</strong> bóng gương (bề mặt bóng thì LGT-001 lấn át). Luôn cần chụp mẫu để xác nhận.</p><h2>Công thức</h2><ul><li>Vết xước: <strong>dark field</strong> — đèn góc thấp, phần phẳng tối, vết xước sáng lên.</li><li>Lõm lồi rất nông: <strong>photometric stereo</strong> — chụp nhiều ảnh với đèn từ nhiều hướng rồi dựng lại pháp tuyến bề mặt; một hướng chiếu không đủ.</li></ul><h2>Sai lầm thường gặp</h2><ul><li>Dùng đèn đồng trục / bright field: vết xước mảnh gần như biến mất.</li><li>Chỉ một hướng chiếu cho vết xước có hướng ngẫu nhiên — xước song song với tia sáng sẽ lọt.</li><li>Photometric stereo trên dây chuyền chạy liên tục mà không tính thời gian chụp nhiều ảnh (THR-003).</li></ul><h2>Ví dụ dự án</h2><p>Minh hoạ: vỏ nhôm phay mờ, xước theo mọi hướng → đèn dark field dạng vòng góc thấp để mọi hướng xước đều bắt sáng; nếu cần phân biệt lõm nông với vết bẩn thì chuyển sang photometric stereo và tính lại nhịp.</p>',
  '<h2>Principle</h2><p>Scratches and dents barely change colour — they change the <strong>orientation</strong> of the surface. To see them you need oblique light, so the tilted spot throws light into (or away from) the camera very differently from the flat surroundings.</p><h2>When it applies</h2><p>The defect type is a scratch or a shallow dent, on a surface that is <strong>not</strong> mirror-like (on glossy surfaces LGT-001 takes over). Always needs sample testing.</p><h2>Formula</h2><ul><li>Scratches: <strong>dark field</strong> — low-angle light, flat areas stay dark, scratches light up.</li><li>Very shallow dents: <strong>photometric stereo</strong> — several shots with light from several directions, then reconstruct the surface normals; one direction is not enough.</li></ul><h2>Common mistakes</h2><ul><li>Coaxial / bright-field light: fine scratches nearly vanish.</li><li>A single light direction for randomly oriented scratches — scratches parallel to the light slip through.</li><li>Photometric stereo on a continuously moving line without budgeting the multiple exposures (THR-003).</li></ul><h2>Project example</h2><p>Illustration: a matte machined aluminium housing with scratches in every direction → a low-angle ring dark field so every orientation catches light; if shallow dents must be told apart from dirt, switch to photometric stereo and recheck the cycle time.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Lighting',
  array['LGT-002'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §4 LGT', 'Bảng tra kinh nghiệm chiếu sáng (src/lib/vision/lighting.ts)'],
  null
),
(
  'rule-thr-002',
  'THR-002 — Băng thông giao tiếp camera',
  'THR-002 — Camera interface bandwidth',
  '<h2>Nguyên lý</h2><p>Mỗi camera đẩy ảnh qua một đường giao tiếp có băng thông hữu hạn. Nếu tốc độ dữ liệu vượt băng thông, ảnh bị rớt khung hoặc camera phải chạy chậm lại — hệ thống không theo kịp dây chuyền. Chỉ nên dùng tối đa 70 % băng thông danh định để chừa cho gói tin lặp và các thiết bị khác chung mạng.</p><h2>Khi nào dùng</h2><p>Khi biết sản lượng (part/phút hoặc takt time) và số pixel mỗi camera. Tầng Yêu cầu đề xuất chuẩn giao tiếp chậm nhất còn đủ; tầng Cấu hình kiểm chính giao tiếp của camera đã chọn.</p><h2>Công thức</h2><p><code>tốc độ dữ liệu = MP × byte/px × ảnh/s</code> (mặc định mono 8 bit = 1 byte/px)<br /><code>tốc độ dữ liệu ≤ 70 % × băng thông</code></p><p>Băng thông dùng trong engine (MB/s): GigE 110 · USB3 350 · 5GigE 550 · 10GigE 1100.</p><h2>Sai lầm thường gặp</h2><ul><li>Tính theo ảnh mono 8 bit rồi mua camera màu hoặc chạy 12 bit — dữ liệu nhân 1,5–3 lần.</li><li>Cắm nhiều camera GigE qua một switch rồi về một cổng máy tính: băng thông chia chung.</li><li>Tin số fps "full resolution" trên datasheet mà không nhân ra MB/s.</li></ul><h2>Ví dụ dự án</h2><p>Minh hoạ (UI_CONTENT màn 6): camera 20 MP chạy 17 fps cần khoảng 340 MB/s, trong khi GigE chỉ khoảng 115 MB/s — thiếu 3 lần. Cặp số "20 MP | GigE | 17 fps" trên một bản vẽ phác là dấu hiệu chưa ai nhân thử.</p>',
  '<h2>Principle</h2><p>Each camera pushes images through an interface with finite bandwidth. If the data rate exceeds it, frames are dropped or the camera must slow down — the system cannot keep up with the line. Use at most 70 % of the nominal bandwidth, leaving room for retransmits and other devices on the network.</p><h2>When it applies</h2><p>When the throughput (parts/min or takt time) and pixels per camera are known. The requirement layer suggests the slowest interface that still fits; the configuration layer checks the chosen camera’s own interface.</p><h2>Formula</h2><p><code>data rate = MP × bytes/px × frames/s</code> (default mono 8-bit = 1 byte/px)<br /><code>data rate ≤ 70 % × bandwidth</code></p><p>Bandwidths used by the engine (MB/s): GigE 110 · USB3 350 · 5GigE 550 · 10GigE 1100.</p><h2>Common mistakes</h2><ul><li>Sizing for mono 8-bit, then buying a colour camera or running 12-bit — 1.5–3× more data.</li><li>Several GigE cameras through one switch into one PC port: they share the bandwidth.</li><li>Trusting the datasheet "full-resolution fps" without converting to MB/s.</li></ul><h2>Project example</h2><p>Illustration (UI_CONTENT screen 6): a 20 MP camera at 17 fps needs about 340 MB/s, while GigE carries only about 115 MB/s — 3× short. "20 MP | GigE | 17 fps" on a concept sketch is a sign nobody multiplied it out.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Throughput',
  array['THR-002'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §4 THR-001/002', 'Hằng số INTERFACE_BANDWIDTH, INTERFACE_MAX_SHARE = 0,7 (src/lib/components/specs.ts, src/lib/vision/requirementAnalysis.ts)'],
  null
),
(
  'rule-thr-003',
  'THR-003 — Ngân sách thời gian chu kỳ',
  'THR-003 — Cycle time budget',
  '<h2>Nguyên lý</h2><p>Mỗi sản phẩm đi qua trạm vision phải được chụp, truyền, xử lý và trả kết quả trước khi sản phẩm kế tiếp tới. Tổng các khoảng thời gian đó phải nằm gọn trong nhịp dây chuyền, và <strong>còn dư</strong> — vì thời gian xử lý thật chỉ biết khi đã có thuật toán.</p><h2>Khi nào dùng</h2><p>Tầng Cấu hình, camera area scan, khi biết sản lượng. Thời gian xử lý chưa đo thì engine dùng số giả định (đánh dấu *).</p><h2>Công thức</h2><p><code>chu kỳ = trigger 1 ms + khung ảnh + truyền ảnh + xử lý + IO 10 ms</code></p><ul><li>Khung ảnh = 1000 ÷ fps (camera không khai fps: giả định 100 ms).</li><li>Truyền ảnh = MB/ảnh ÷ băng thông giao tiếp.</li><li>Xử lý: giả định 300 ms/ảnh (truyền thống), 800 ms/ảnh (deep learning) — thay bằng số đo thật khi có.</li><li>Nhịp = 60000 ÷ part/phút. Vượt nhịp → không đạt; dư dưới 30 % → cảnh báo.</li></ul><h2>Sai lầm thường gặp</h2><ul><li>Chỉ so fps của camera với sản lượng, quên truyền ảnh và xử lý.</li><li>Tin số xử lý giả định như số đo — phải đo lại với thuật toán thật trên máy thật.</li><li>Quên các lần chụp nhiều ảnh mỗi sản phẩm (nhiều góc, photometric stereo).</li></ul><h2>Ví dụ dự án</h2><p>Minh hoạ (test engine): 30 part/phút → nhịp 2000 ms; camera 23 fps GigE ảnh 5 MB → 1 + 43,5 + 45,6 + 300* + 10 = 400 ms, dư 80 % → đạt, với ghi chú số 300 ms là giả định.</p>',
  '<h2>Principle</h2><p>Every part passing the vision station must be captured, transferred, processed and reported before the next part arrives. The sum of those times must fit inside the line takt, <strong>with headroom</strong> — because real processing time is only known once the algorithm exists.</p><h2>When it applies</h2><p>Configuration layer, area-scan cameras, once throughput is known. If processing time has not been measured, the engine uses assumed figures (marked *).</p><h2>Formula</h2><p><code>cycle = trigger 1 ms + frame + transfer + processing + IO 10 ms</code></p><ul><li>Frame = 1000 ÷ fps (camera without fps data: 100 ms assumed).</li><li>Transfer = MB per image ÷ interface bandwidth.</li><li>Processing: 300 ms/image assumed (traditional), 800 ms/image (deep learning) — replace with measured figures when available.</li><li>Takt = 60000 ÷ parts/min. Over takt → fail; under 30 % headroom → warning.</li></ul><h2>Common mistakes</h2><ul><li>Comparing only camera fps with throughput, forgetting transfer and processing.</li><li>Treating the assumed processing time as measured — re-measure with the real algorithm on the real PC.</li><li>Forgetting multiple shots per part (several angles, photometric stereo).</li></ul><h2>Project example</h2><p>Illustration (engine test): 30 parts/min → 2000 ms takt; 23 fps GigE camera, 5 MB images → 1 + 43.5 + 45.6 + 300* + 10 = 400 ms, 80 % headroom → pass, noting that 300 ms is assumed.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Throughput',
  array['THR-003'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §8.1 THR-003', 'Hằng số CYCLE_DEFAULTS, CYCLE_MIN_MARGIN = 0,3 (src/lib/vision/configurationRules.ts)'],
  null
),
(
  'rule-ai-001',
  'AI-001 — Xử lý ảnh truyền thống trước, deep learning sau',
  'AI-001 — Traditional vision first, deep learning second',
  '<h2>Nguyên lý</h2><p>Xử lý ảnh truyền thống (ngưỡng, biên, blob, so mẫu) ổn định, giải thích được, chạy nhanh và không cần hàng nghìn ảnh lỗi để huấn luyện. Deep learning chỉ đáng dùng khi lỗi <strong>biến thiên hình dạng / màu sắc lớn</strong> đến mức không mô tả được bằng ngưỡng cố định. Thứ tự ưu tiên: ổn định → chính xác → tốc độ → bảo trì → dễ triển khai → chi phí.</p><h2>Khi nào dùng</h2><p>Mọi bài có phát hiện lỗi, theo ô "độ biến thiên của lỗi":</p><ul><li>Thấp hoặc trung bình → AI-001: xử lý truyền thống (đạt).</li><li>Cao → AI-002: ứng viên deep learning, cần bộ ảnh mẫu để xác nhận.</li><li>Chưa rõ → AI-001 kèm cảnh báo: hỏi lại khách.</li></ul><h2>Công thức</h2><p>Không có công thức — đây là luật kinh nghiệm. Hệ quả tính được: bài deep learning dùng thời gian xử lý giả định 800 ms/ảnh thay vì 300 ms trong THR-003, và cần GPU khi chọn máy tính.</p><h2>Sai lầm thường gặp</h2><ul><li>Chọn deep learning vì "hiện đại" cho lỗi mà một ngưỡng đơn giản đã bắt được — tốn dữ liệu, khó giải thích khi khách hỏi vì sao loại.</li><li>Hứa deep learning khi khách chưa có ảnh lỗi thật để huấn luyện.</li><li>Dùng deep learning để bù cho chiếu sáng kém — sửa đèn trước.</li></ul><h2>Ví dụ dự án</h2><p><strong>GT-001</strong>: khách chưa nêu độ biến thiên của lỗi → AI-001 kèm cảnh báo, kỹ sư phải hỏi lại trước khi chốt thuật toán. <strong>GT-002</strong> (bụi trên lớp mạ): biến thiên cao → AI-002, ứng viên deep learning, phải thu ảnh mẫu trước khi chốt.</p>',
  '<h2>Principle</h2><p>Traditional vision (thresholds, edges, blobs, template matching) is stable, explainable, fast, and needs no thousands of defect images to train. Deep learning is only worth it when defects <strong>vary widely in shape or colour</strong> — too much to describe with fixed thresholds. Priority order: stability → accuracy → speed → maintainability → ease of deployment → cost.</p><h2>When it applies</h2><p>Every task with defect detection, based on the "defect variability" field:</p><ul><li>Low or medium → AI-001: traditional vision (pass).</li><li>High → AI-002: deep-learning candidate, needs a sample image set to confirm.</li><li>Unknown → AI-001 with a warning: ask the customer.</li></ul><h2>Formula</h2><p>No formula — this is an experience rule. The computed consequence: deep-learning tasks use an assumed 800 ms/image processing time instead of 300 ms in THR-003, and need a GPU when choosing the PC.</p><h2>Common mistakes</h2><ul><li>Choosing deep learning because it is "modern" for defects a simple threshold already catches — data-hungry and hard to explain when the customer asks why a part was rejected.</li><li>Promising deep learning before the customer has real defect images to train on.</li><li>Using deep learning to compensate for poor lighting — fix the light first.</li></ul><h2>Project example</h2><p><strong>GT-001</strong>: the customer did not state defect variability → AI-001 with a warning; the engineer must ask before committing to an algorithm. <strong>GT-002</strong> (dust on plating): high variability → AI-002, deep-learning candidate; collect sample images before committing.</p>',
  (select id from public.categories where slug = 'rule-notes'),
  'member', 'ruleNote', 'Algorithm',
  array['AI-001'],
  array['docs/VISION_ENGINEER_SPEC_V1.1.md §4 AI-001/002', 'CLAUDE.md §4 — chỉ gợi ý deep learning khi rule-based không đáp ứng'],
  null
)
on conflict (slug) do nothing;
